version: 2
updates:
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      minor-and-patch:
        update-types: ['minor', 'patch']
    ignore:
      - dependency-name: 'react-dnd'
      - dependency-name: 'react-dnd-html5-backend'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
