version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 2
    commit-message:
      prefix: 'npm'
    labels:
      - 'npm'
      - 'dependencies'
    package-exceptions:
      - 'react-dnd-html5-backend'
      - 'react-dnd'
